const ENGLISH_LOCALIZATIONS = {
  'settings': 'Settings',
  'language': 'Language',
  'name': 'Name',
  'description': 'Description',
  'relatedAddress': 'Related address',
  'addNote': 'Add note',
  'editNote': 'Edit note',
  'addAddress': 'Add address',
  'editAddress': 'Edit address',
  'city': 'City',
  'street': 'Street',
  'houseNumber': 'House number',
  'add': 'Add',
  'edit': 'Edit',
  'delete': 'Delete',
  'hungarian': 'Hungarian',
  'english': 'English',
  'fieldIsMandatory': "The field is mandatory"
};