const HUNGARIAN_LOCALIZATIONS = {
  'settings': 'Beállítások',
  'language': 'Nyelv',
  'name': 'Név',
  'description': 'Leírás',
  'relatedAddress': 'Hozzátartozó cím',
  'addNote': 'Jegyzet hozzáadása',
  'editNote': 'Jegyzet szerkesztése',
  'city': 'Város',
  'street': 'Utca',
  'houseNumber': 'Ház szám',
  'addAddress': 'Cím hozzáadása',
  'editAddress': 'Cím szerkesztése',
  'add': 'Hozzáadás',
  'edit': 'Szerkesztés',
  'delete': 'Törlés',
  'hungarian': 'Magyar',
  'english': 'Angol',
  'fieldIsMandatory': "A mező kitöltése kötelező"
};